routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->namespace('Admin\\')->name('admin.')->group(function () {
    Auth::routes();

    Route::middleware('auth', 'is_admin')->group(function () {
        Route::post('pizzas/{pizza}/restore', 'PizzaController@restore')->name('pizzas.restore');
        Route::resource('pizzas', 'PizzaController');
        Route::resource('orders', 'OrderController')->only('index', 'show');

        Route::view('', 'admin.home')->name('home');
    });
});

Route::fallback(function () {
    return view('home');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Vinkla\Hashids\Facades\Hashids;

class Order extends Model
{
    protected $fillable = [
        'full_name', 'address', 'zip_code', 'city', 'notes', 'cart_data'
    ];

    protected $casts = [
        'cart_data' => 'json'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getHashAttribute()
    {
        return Hashids::connection('alternative')->encode($this->id);
    }

    public function getFullAddressAttribute()
    {
        return sprintf('%s, %s %s', $this->address, $this->zip_code, $this->city);
    }

    public function getTotalAttribute()
    {
        return implode(' - ', $this->cart_data['total']);
    }

    public function getDeliveryAttribute()
    {
        return implode(' - ', $this->cart_data['delivery'] ?? []);
    }

    public function getDataAttribute()
    {
        return ['id' => $this->hash];
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Order;

class OrderController extends Controller
{
    protected $name;
    protected $pluralName;

    public function __construct()
    {
        $this->name = trans_choice('admin.models.order', 1);
        $this->pluralName = trans_choice('admin.models.order', 2);
    }

    public function index()
    {
        $orders = Order::paginate(static::PAGINATION_SIZE);
        $title = $this->pluralName;
        return view('admin.orders.index', compact('title', 'orders'));
    }

    public function show(Order $order)
    {
        $title = sprintf('%s: %s', $this->name, $order->hash);
        return view('admin.orders.show', compact('title', 'order'));
    }
}

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Cart;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\OrderRequest;
use App\Order;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    public function store(OrderRequest $request)
    {
        $data = DB::transaction(function () use ($request) {
            $order = new Order($request->validated());
            /** @var Cart $cart */
            $cart = $request->cart;

            $order->cart_data = $cart->data;
            if ($user = $request->user('api')) {
                $order->user()->associate($user);
            }
            $order->save();

            $cart->pizzas()->detach();
            $cart->load('pizzas');

            return ['order' => $order->data, 'cart' => $cart->data];
        });
        return $data;
    }
}

resources/views/admin/orders/empty.blade.php
<tr class="bg-warning text-center">
    <th colspan="5">@lang('admin.prompts.empty', ['name' => trans_choice('admin.models.order', 1)])</th>
</tr>

resources/views/admin/orders/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="d-flex align-items-center">
        <h1 class="m-0 text-dark">{{ $title }}</h1>
    </div>
@stop

@section('content')
    @component('admin.components.table', ['rows' => $orders])
        @slot('thead')
            <tr>
                <th>@lang('admin.fields.order_id')</th>
                <th>@lang('admin.fields.full_name')</th>
                <th>@lang('admin.fields.address')</th>
                <th>@lang('admin.fields.total')</th>
                <th class="text-center"><i class="fas fa-fw fa-cog"></i></th>
            </tr>
        @endslot
        @each('admin.orders.row', $orders, 'order', 'admin.orders.empty')
    @endcomponent
@stop

resources/views/admin/orders/row.blade.php
<tr>
    <td>{{ $order->hash }}</td>
    <td>{{ $order->full_name }}</td>
    <td>{{ $order->full_address }}</td>
    <td>{{ $order->total }}</td>
    <td class="text-center">
        <a href="{{ route('admin.orders.show', $order) }}" class="btn btn-info btn-xs">
            <i class="fas fa-fw fa-eye mr-1"></i>
            @lang('admin.actions.show', ['name' => ''])
        </a>
    </td>
</tr>

resources/views/admin/orders/show.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="d-flex align-items-center">
        <h1 class="m-0 text-dark">{{ $title }}</h1>
        <a href="{{ route('admin.orders.index') }}" class="btn btn-warning btn-sm ml-auto">
            <i class="fas fa-fw fa-chevron-left mr-1"></i>
            @lang('admin.actions.back')
        </a>
    </div>
@stop

@section('content')
    <div class="card">
        <div class="card-header table-responsive p-0">
            <table class="table table-striped table-bordered table-head-fixed text-nowrap m-0">
                <thead>
                <tr>
                    <th>#</th>
                    <th>{{ trans_choice('admin.models.pizza', 1) }}</th>
                    <th>@lang('admin.fields.quantity')</th>
                    <th>@lang('admin.fields.total')</th>
                </tr>
                </thead>
                <tbody>
                @foreach($order->cart_data['pizzas'] as $i => $pizza)
                    <tr>
                        <td>{{ $i + 1 }}</td>
                        <td>{{ $pizza['name'] }}</td>
                        <td>{{ $pizza['quantity'] }}</td>
                        <td>{{ implode(' - ', $pizza['price']) }}</td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th colspan="3" class="text-right">@lang('admin.fields.delivery')</th>
                    <th>{{ $order->delivery }}</th>
                </tr>
                <tr>
                    <th colspan="3" class="text-right">@lang('admin.fields.total')</th>
                    <th>{{ $order->total }}</th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@stop