routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->namespace('Admin\\')->name('admin.')->group(function () {
    Auth::routes();

    Route::middleware('auth', 'is_admin')->group(function () {
        Route::post('pizzas/{pizza}/restore', 'PizzaController@restore')->name('pizzas.restore');
        Route::resource('pizzas', 'PizzaController');
        Route::resource('orders', 'OrderController')->only('index', 'show');

        Route::view('', 'admin.home')->name('home');
    });
});

Route::fallback(function () {
    return view('home');
});

app/Pizza.php
<?php

namespace App;

use Akaunting\Money\Money;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use QCod\ImageUp\HasImageUploads;

class Pizza extends Model
{
    use SoftDeletes,
        Sluggable,
        HasImageUploads;

    protected static $imageFields = [
        'image' => [
            'path' => 'pizzas'
        ]
    ];

    protected $fillable = [
        'name', 'description', 'price', 'price_currency'
    ];

    public static function findBySlug(string $slug)
    {
        return static::where('slug', $slug)->firstOrFail();
    }

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name',
                'includeTrashed' => true,
                'onUpdate' => true
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getShortDescriptionAttribute(): ?string
    {
        return Str::limit($this->description, 140);
    }

    public function getPriceTextAttribute(): string
    {
        return $this->getPriceMoneyAttribute()->format();
    }

    public function getPriceMoneyAttribute(): Money
    {
        return money($this->price, $this->price_currency);
    }

    public function getImageUrlAttribute(): ?string
    {
        return $this->image ? $this->imageUrl('image') : null;
    }

    public function getDataAttribute(): array
    {
        return [
            'id' => $this->slug,
            'name' => $this->name
        ];
    }
}

app/Http/Controllers/Admin/PizzaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\PizzaRequest;
use App\Pizza;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

class PizzaController extends Controller
{
    protected $name;
    protected $pluralName;

    public function __construct()
    {
        $this->name = trans_choice('admin.models.pizza', 1);
        $this->pluralName = trans_choice('admin.models.pizza', 2);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $pizzas = Pizza::withTrashed()->paginate(static::PAGINATION_SIZE);
        $title = $this->pluralName;
        return view('admin.pizzas.index', compact('title', 'pizzas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $title = trans('admin.actions.create', ['name' => $this->name]);
        return $this->showForm($title, new Pizza);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PizzaRequest $request
     * @return Response
     */
    public function store(PizzaRequest $request)
    {
        return $this->update($request, new Pizza);
    }

    /**
     * Display the specified resource.
     *
     * @param Pizza $pizza
     * @return Response
     */
    public function show(Pizza $pizza)
    {
        $title = sprintf('%s: %s', $this->name, $pizza->name);
        return view('admin.pizzas.show', compact('title', 'pizza'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Pizza $pizza
     * @return Response
     */
    public function edit(Pizza $pizza)
    {
        $title = trans('admin.actions.edit', ['name' => $this->name]);
        return $this->showForm($title, $pizza);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PizzaRequest $request
     * @param Pizza $pizza
     * @return Response
     */
    public function update(PizzaRequest $request, Pizza $pizza)
    {
        $pizza->fill($request->validated())->saveOrFail();
        return $this->redirectIndex();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Pizza $pizza
     * @return Response
     */
    public function destroy(Pizza $pizza)
    {
        $pizza->delete();
        return $this->redirectIndex();
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param Pizza $pizza
     * @return Response
     */
    public function restore($pizza)
    {
        Pizza::withTrashed()->firstWhere('slug', $pizza)->restore();
        return $this->redirectIndex();
    }

    protected function showForm(string $title, Pizza $pizza): View
    {
        return view('admin.pizzas.form', compact('title', 'pizza'));
    }

    protected function redirectIndex()
    {
        flash(trans('admin.prompts.success'))->success();
        return redirect()->route('admin.pizzas.index');
    }
}

app/Http/Controllers/Api/PizzaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Pizza;

class PizzaController extends Controller
{
    public function index()
    {
        return Pizza::all()->map->data;
    }

    public function show(Pizza $pizza)
    {
        return $pizza->only('name', 'description', 'price_text', 'image_url');
    }
}

resources/views/admin/pizzas/empty.blade.php
<tr class="bg-warning text-center">
    <th colspan="5">@lang('admin.prompts.empty', ['name' => trans_choice('admin.models.pizza', 1)])</th>
</tr>

resources/views/admin/pizzas/form.blade.php
@extends('adminlte::page')

@section('plugins.CustomFileInput', true)

@section('title', $title)

@section('content_header')
    <div class="d-flex align-items-center">
        <h1 class="m-0 text-dark">{{ $title }}</h1>
        <a href="{{ route('admin.pizzas.index') }}" class="btn btn-warning btn-sm ml-auto">
            <i class="fas fa-fw fa-chevron-left mr-1"></i>
            @lang('admin.actions.back')
        </a>
        @if($pizza->id)
            <a href="{{ route('admin.pizzas.show', $pizza) }}" class="btn btn-info btn-sm ml-2">
                <i class="fas fa-fw fa-eye mr-1"></i>
                @lang('admin.actions.show', ['name' => $pizza->name])
            </a>
            <a href="{{ route('admin.pizzas.destroy', $pizza) }}" class="btn btn-danger btn-sm ml-2"
               data-destroy="@lang('admin.prompts.delete')">
                <i class="fas fa-fw fa-trash mr-1"></i>
                @lang('admin.actions.delete', ['name' => $pizza->name])
            </a>
        @endif
    </div>
@stop

@section('content')
    @component('admin.components.form')
        @slot('open')
            @if($pizza->id)
                {!! Form::open()->route('admin.pizzas.update', [$pizza])->method('put')->multipart()->fill($pizza) !!}
            @else
                {!! Form::open()->route('admin.pizzas.store')->multipart()->fill($pizza) !!}
            @endif
        @endslot
        <div class="row">
            <div class="col">
                {!! Form::text('name', trans('admin.fields.name')) !!}
            </div>
            <div class="col-md-5 col-xl-3">
                <div class="row">
                    <div class="col">
                        {!! Form::text('price', trans('admin.fields.price')) !!}
                    </div>
                    <div class="col-4">
                        {!! Form::select('price_currency', trans('admin.fields.currency'), $currencies) !!}
                    </div>
                </div>
            </div>
        </div>
        {!! Form::textarea('description', trans('admin.fields.description'))->attrs(['rows' => 5]) !!}
        {!! Form::file('image', trans('admin.fields.image'))->attrs(['data-file' => trans('admin.actions.choose', ['name' => trans('admin.fields.image')])]) !!}
        <div data-preview="#inp-image">
            @if($pizza->image)
                <img src="{{ $pizza->imageUrl('image') }}" class="img-thumbnail" alt="preview">
            @endif
        </div>
    @endcomponent
@stop

resources/views/admin/pizzas/index.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="d-flex align-items-center">
        <h1 class="m-0 text-dark">{{ $title }}</h1>
        <a href="{{ route('admin.pizzas.create') }}" class="btn btn-success btn-sm ml-auto">
            <i class="fas fa-fw fa-plus mr-1"></i>
            @lang('admin.actions.create', ['name' => trans_choice('admin.models.pizza', 1)])
        </a>
    </div>
@stop

@section('content')
    @component('admin.components.table', ['rows' => $pizzas])
        @slot('thead')
            <tr>
                <th>@lang('admin.fields.name')</th>
                <th>@lang('admin.fields.description')</th>
                <th>@lang('admin.fields.price')</th>
                <th>@lang('admin.fields.deleted')</th>
                <th class="text-center"><i class="fas fa-fw fa-cog"></i></th>
            </tr>
        @endslot
        @each('admin.pizzas.row', $pizzas, 'pizza', 'admin.pizzas.empty')
    @endcomponent
@stop

resources/views/admin/pizzas/row.blade.php
<tr>
    <td>{{ $pizza->name }}</td>
    <td>{{ $pizza->short_description }}</td>
    <td>{{ $pizza->price_text }}</td>
    <td class="text-center">
        <i class="fas fa-fw {{ $pizza->deleted_at ? 'fa-check text-success' : 'fa-times text-danger' }}"></i>
    </td>
    <td class="text-center">
        @if($pizza->deleted_at)
            <a href="{{ route('admin.pizzas.restore', $pizza) }}" class="btn btn-warning btn-xs ml-2"
               data-restore="@lang('admin.prompts.restore')">
                <i class="fas fa-fw fa-redo mr-1"></i>
                @lang('admin.actions.restore', ['name' => ''])
            </a>
        @else
            <a href="{{ route('admin.pizzas.show', $pizza) }}" class="btn btn-info btn-xs">
                <i class="fas fa-fw fa-eye mr-1"></i>
                @lang('admin.actions.show', ['name' => ''])
            </a>
            <a href="{{ route('admin.pizzas.edit', $pizza) }}" class="btn btn-primary btn-xs ml-2">
                <i class="fas fa-fw fa-edit mr-1"></i>
                @lang('admin.actions.edit', ['name' => ''])
            </a>
            <a href="{{ route('admin.pizzas.destroy', $pizza) }}" class="btn btn-danger btn-xs ml-2"
               data-destroy="@lang('admin.prompts.delete')">
                <i class="fas fa-fw fa-trash mr-1"></i>
                @lang('admin.actions.delete', ['name' => ''])
            </a>
        @endif
    </td>
</tr>

resources/views/admin/pizzas/show.blade.php
@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <div class="d-flex align-items-center">
        <h1 class="m-0 text-dark">{{ $title }}</h1>
        <a href="{{ route('admin.pizzas.index') }}" class="btn btn-warning btn-sm ml-auto">
            <i class="fas fa-fw fa-chevron-left mr-1"></i>
            @lang('admin.actions.back')
        </a>
        <a href="{{ route('admin.pizzas.edit', $pizza) }}" class="btn btn-primary btn-sm ml-2">
            <i class="fas fa-fw fa-edit mr-1"></i>
            @lang('admin.actions.edit', ['name' => $pizza->name])
        </a>
        <a href="{{ route('admin.pizzas.destroy', $pizza) }}" class="btn btn-danger btn-sm ml-2"
           data-destroy="@lang('admin.prompts.delete')">
            <i class="fas fa-fw fa-trash mr-1"></i>
            @lang('admin.actions.delete', ['name' => $pizza->name])
        </a>
    </div>
@stop

@section('content')
    <div class="card pizza-detail">
        <div class="card-body">
            @if($pizza->image)
                <img src="{{ $pizza->imageUrl('image') }}" class="float-left" alt="{{ $pizza->name }}">
            @endif
            <h5>{{ $pizza->name }}</h5>
            <p class="m-0">{{ $pizza->description ?? trans('admin.prompts.no_description') }}</p>
        </div>
    </div>
@stop